### PR TITLE
for installing in include/pv follow  pvaClientCPP

### PR DESCRIPTION
**Pull request by mrkraimer**
Follow the way Michael installed header files from pvaClientCPP.

Note that
INSTALL_INCLUDE = $(INSTALL_LOCATION)/include/pv
No longer appears in any Makefile or config file.

### CODE REVIEW

**Comment by anjohnson** [comment]
Looks OK to me.

**Comment by mrkraimer** [comment]
Try to make rtems and windows build

Michael said:
The issue here appears to be that test/rtemsTestHarness.c wants pvDataAllTests() while test/pvDatabaseAllTests.c provides pvDatabaseAllTests().

and
I won't claim to be an expert on the whole dllimport/export business
(especially wrt. inline code), but I think I see two issues here.  One
is a missing
> #define epicsExportSharedSymbols
Try adding this in testPVCopy.cpp just before the include of powerSupply.h.
Also, in powerSupply.h, since this code is in the executable and not in
a library you shouldn't qualify it 'epicsShareClass'.

**Comment by anjohnson** [comment]
I just fixed the RTEMS build on master directly; working on the Windows problem now. Unfortunately this pull request branch now has a conflict with master which you'll have to fix manually. Github tells you how to do that, click the 'view command line instructions' link above when viewing this comment on github for help.

**Comment by mrkraimer** [comment]
On 02/03/2016 01:11 PM, Andrew Johnson wrote:
>
> I just fixed the RTEMS build on master directly; working on the 
> Windows problem now. Unfortunately this pull request branch now has a 
> conflict with master which you'll have to fix manually. Github tells 
> you how to do that, click the 'view command line instructions' link 
> above when viewing this comment on github for help.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/epics-base/pvDatabaseCPP/pull/9#issuecomment-179384402>.
>


I did a

git pull https://github.com/epics-base/exampleCPP.git

And then edited test/pvDatabaseAllTests.c so that conflicts are resolved.

Then I do

mrk> git add test/pvDatabaseAllTests.c
Then I see

mrk> git status
On branch master
Your branch is up-to-date with 'origin/master'.
You have unmerged paths.
   (fix conflicts and run "git commit")

Changes to be committed:

     modified:   test/pvDatabaseAllTests.c

Unmerged paths:
   (use "git add <file>..." to mark resolution)

     both modified:   test/rtemsTestHarness.c

mrk> git commit -m "resolve conflict"
U    test/rtemsTestHarness.c
error: commit is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.
mrk>

What now?
Note that test/pvDatabaseAllTests.c does not show any conflicts.

**Comment by anjohnson** [comment]
A hint about git that I read recently: Read the output from `git status` carefully, as it usually tells you exactly what you need to do in many circumstances. In this case I think you just have to do `git add test/rtemsTestHarness.c` before you do the commit. If I'm wrong and that doesn't work then I think someone else who knows git better than I do will have to answer.

**Comment by mrkraimer** [comment]
On 02/03/2016 04:48 PM, Andrew Johnson wrote:
>
> A hint about git that I read recently: Read the output from |git 
> status| carefully, as it usually tells you exactly what you need to do 
> in many circumstances. In this case I think you just have to do |git 
> add test/rtemsTestHarness.c| before you do the commit. If I'm wrong 
> and that doesn't work then I think someone else who knows git better 
> than I do will have to answer.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/epics-base/pvDatabaseCPP/pull/9#issuecomment-179487499>.
>

Did try to follow the instruction shown on github but must have done 
something wrong.

But what did work is to copy the version of test/rtemsTestHarness.c from 
epics_base to mrkraimer.
Then I did a git add, commit, and push.

That fixed the problem.

On gihub I will do the merge.

**Pull request merged**
