### PR TITLE
Issue53

### PR DESCRIPTION
**Pull request by mrkraimer**
This fixes the problem reported by issue 53

### CODE REVIEW

**Comment by ralphlange** [comment]
I don't really like the idea of two methods of objects in a hierarchical relation calling each other with just a flag to avoid looping.
Smells like a kludge that covers up a flaw of a bad design... Is there a document somewhere showing the relations, ownership and life cycles of the parts of a pvDatabase?

My approach would have been to add a client->detach() method that takes a raw pointer, and call that one from the pvRecord destructor.

**Comment by mrkraimer** [comment]
On 2/11/20 6:52 AM, Ralph Lange wrote:
>
> I don't really like the idea of two methods of objects in a 
> hierarchical relation calling each other with just a flag to avoid 
> looping.
> Smells like a kludge that covers up a flaw of a bad design... Is there 
> a document somewhere showing the relations, ownership and life cycles 
> of the parts of a pvDatabase?
>
>
I pushed changes so that pvDatabase::removeRecord and pvRecord::remove 
no longer call each other directly.
Instead each has a private method to do the work it requires.
Each is a friend of the other so that each can call the other's private 
method.

**Comment by mrkraimer** [comment]
If I do not hear any objections I will merge tomorrow  2020.02.18

**Comment by ralphlange** [comment]
I still don't see why listener->unlisten() and client->detach() need a shared_ptr to the record.
Why do the listener and the client need *shared ownership* of the record just for detaching themselves?
If these two methods were working with a raw pointer, they could simply be called from the pvRecord destructor.

Again, I would like to see a description of the ownership concept across the pvDatabase classes and their life cycles. Who has shared and weak pointers to what at which phase? Is this part of the documentation?

**Comment by mrkraimer** [comment]
On 2/17/20 4:40 PM, Ralph Lange wrote:
>
> I still don't see why listener->unlisten() and client->detach() need a 
> shared_ptr to the record.
> Why do the listener and the client need /shared ownership/ of the 
> record just for detaching themselves?
> If these two methods were working with a raw pointer, they could 
> simply be called from the pvRecord destructor.
>

PVDatabase currently exposes NO raw pointers to anything.
It always uses shared_ptr and weak_ptr.
Note that both shared_ptr and weak_ptr are thread safe.
If raw pointers are exposed thread safety is a big problem.

> Again, I would like to see a description of the ownership concept 
> across the pvDatabase classes and their life cycles. Who has shared 
> and weak pointers to what at which phase? Is this part of the 
> documentation?
>

PVDatabase is the only thing that keeps a shared_ptr to each PVRecord.
Everything else that uses a PVRecord has a weak_ptr to PVRecords.
Thus when a PVRecord is removed from the PVDatabase nothing except code 
that has a weak_ptr.lock should have a
shared_ptr to the PVRrecord.

This shortly after the database removes the record the destructor for 
the record is called.

I still plan to merge this request tomorrow.

**Comment by ralphlange** [comment]
> Thus when a PVRecord is removed from the PVDatabase nothing except code
> that has a weak_ptr.lock should have a shared_ptr to the PVRrecord.

This was obviously not true and the cause for the original problem: The pvRecord destructor was using shared_from_this() creating a shared_ptr from a naked pointer.

Be careful: only the control block part of shared_ptr and weak_ptr are thread safe. Access to the managed object is not, and data races occur if two threads are accessing the same object through their shared pointers.

I will not keep you from merging this "fix". Thanks for taking time to understand the problem.

**Comment by mrkraimer** [comment]
What caused the problem was calling code that had a weak_ptr to a PVRecord from the  PVRecord destructor.

I googled share_from_this and never found anything that said it caused an exception if called from the PVRecord destructor. I did find warnings that it did not work if called from the PVRecord constructor.
I also fixed a couple of  instances where a method accessing a std::map was not protected by

    epicsGuard<epics::pvData::Mutex> guard(mutex);

**Pull request merged**
